language: go

script:
  - go test -race -v ./color/color/...
  - go test -race -v ./app/app/...

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip

install:
  - go get github.com/lucasb-eyer/go-colorful
